apiVersion: v1
kind: Secret
metadata:
    name: router-secrets
    namespace: jarvis2-router
type: Opaque
stringData:
    LOBSTER_TOKEN: ENC[AES256_GCM,data:M07aiSn+xxBsUQCkssCg5l4XX7hFwP/RxwoDv0qHPNWDJym2AydUhe2aP81raZMU9eMJ/RYu49kaoh+I54V281N+rDn1kk4s,iv:Elq4CozbX5x0fekZ+Eeu8/1abpjEsl1ufOZSGCXQDno=,tag:7Wtrb9CLI1HKzJhFCq2QFw==,type:str]
    STORAGEBOX_HOST: ENC[AES256_GCM,data:9ZExv6tG/+aqGJXMlkSYnfXT01aHXufLOEI=,iv:uf/hHAbFKQj1CnS00SWpYlt2/GjthHqr07W13yor6Qs=,tag:jKYFb0zAQjtZKCzFktPDxg==,type:str]
    STORAGEBOX_USER: ENC[AES256_GCM,data:+GX/NJkK3g==,iv:AawyUJXqiln9GBDi0mdvtUkuo3V5EK9In9heoNdk5UQ=,tag:1SnNXuGptsXpoAkexuruAw==,type:str]
    STORAGEBOX_PASSWORD: ENC[AES256_GCM,data:A1/GSxxhyp9uKdTX5kadY9PnJuDjcEZHJ2I4AsJGHjE=,iv:NIACN43v5NKJkQzFahumYRQEzt0HKPTZsbWgj3m5Up8=,tag:voh3EnwDciaChLQk/sZQ4g==,type:str]
    FLY_READ_TOKEN: ENC[AES256_GCM,data:7iTKurb90xSFJGv7evLDAdzNeiwQVrP17HvZO63HJcggqFcgS2rtCfMAczYjtY/TtP53Y08uky3GHIue30txZLW7t86vQxFT9xIj/C3jz4xJ/pjUBkogHKzTneiYR4DHPYA2YEG/IQ3dIufNQlv+Tw11sLTqEiq/TXcHKD5QucjkjGZcdXIGor0BxZJ30ywyPN3OsvrpCu2Y/iXSz70K3m7Y6GvMplffh9wgJfz5Qwt14SnLpZzuZX441hyPlBdnBURNyPdL9IMEvjvZhW5EN+HRGvroQnjlOk08IzaZoLewMUahBwFWcNs1v4wD58gAeSjJkiPvkrcVRFVmTqPt7KQ+bDkoXdvsvrkNZlAq2L2b82eJ/fG3eQQhGjfxdl+ibFEptDklXwG2bM4pvyIn2+VWSh7rZqqcg2HvLc6r7EqzAb+rLJGYe6MM7CT/CJWhBZKR3QgNtuPEqViR7l46sU8mQhjw4UDXpSPqcinOQnQz4cUmnCLQMK0RlcfwBjNkQj/KeI+KXEQfiqrz3IZ1r5hLz//GIyOhEKQd3voeR99+IaQ6RmnsJlQwKNhytDT395c1wp4NHALTIQYoGzk6a/SqSpZvGtnYlVy9CfWYafmqFteC+T/HY0MN0oIPq1PhpwP8kXKc/jnmLVhjVPTsIf1FdajxTX+s2SCGQi1VGrW6XjP1QTCDweQ5+BugTMRgp3sabouYg6ub1ZK1x5rHpmM59qO67f+4Tm+Hk+e/tMtdlClsZ17Q+GoapyOXrabLm1UwTC+pd2CuGMGPzFzVGHWqYM6QmVHN8f1BGWtnslKWfQxhgU+Npm254h5IZHxatJJhS7R6p4Td63jYSk/H4Blrw7cwtS+xTYDZ8U4t5oGrxr8=,iv:fLj/0noxv3hp0FHfxeiI37Za5hCASb0TVarQmqgGnDo=,tag:mE1KmdKjp2tZEY3WD2B5jA==,type:str]
    JARVIS1_CREDENTIALS_ID: ENC[AES256_GCM,data:VLLSmVcAsDCrLtD5D6Dcjc0r8vqQ77S9UQSaHgLknDaOWY+WI7QS,iv:lL2+vQcuzpeBTVzoWd+BM+vfgitidA1ISJfR3SpQvj8=,tag:VNf9noza1qisO6myf8l7Dg==,type:str]
    JARVIS1_CREDENTIALS_SECRET: ENC[AES256_GCM,data:rQyy4aTRVmwliAG42jePj7o+Geuou0tAxaHgEfE4SWwmM29UvZL36VA/5fC+eG42SA8HvHrw,iv:6EgVxRoyotOcVDqUPPTXsRKVsoViSM4UFcpbgbhZ/pg=,tag:xr88ucmE9f4i7R2sF6EsgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISHhEYzIwWHlvaXc4eHRI
            UjZseVFSeWl6anFrOXJmWGZQYVJyWkJNTmpzCkdvSnhuYTJTTWc3ODgvb3lGR2t6
            Tk5IdVVjeFh2dWVLdy9KQVU5R1VDcWcKLS0tIFJGWnNRNmNEUUVOdFQzSWtNSjV0
            V2ZRaGhUV0JTNExPZXlNTDQvemp6ZXMK1U/vKCXCJ5yWb7OLfUdFRugqlXTqvhT/
            duyukN/+FYculnN4+E4/Ud7ZzVB0uSOSsCMyy9Z7X5OBveXJ5ASl6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aft9s8atepzmgx8qfjpjndanxaj739k3y9vctycdtgxdhlg3uc8q4vy7pa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T08:22:23Z"
    mac: ENC[AES256_GCM,data:AKYVa9FrMgS2yheF7AlNP8k73tl96ugRptZs2Dmva/mc0zFjoNItWzSL71Oer268W/xoTljcayUcgFC8F2jMVBGeli6XN1fr2UPJKRCbefIW/jbW7/xRXmEkksu7vppIBYrFC/Y/r1yOMNV4iUZrSpnYaRCCLZMtyKqJP1nlwBM=,iv:KH9XpUOZac3MIHpP3mWyjvBhd4g4fXgs1WRAzF9Vhy8=,tag:J9dhO6u1ahrygXEcYwiUyA==,type:str]
    version: 3.13.3
