apiVersion: v1
kind: Secret
metadata:
    name: router-secrets
    namespace: jarvis2-router
type: Opaque
stringData:
    LOBSTER_TOKEN: ENC[AES256_GCM,data:HbTVCOlXgv5BaHBvricYDU+/DRBGohah+xkNUQVsVBTdfao2jaTOeNxEv6Sjbj5XJR6GurIwE+XY/j/sZhqyRM6KqLH0Vjdc,iv:x2rzI6IRpjW4UE4rr4YKBrLgEiu+eJkbQOe+OWeCOWQ=,tag:Lmz/CsEoZwOVBj2W1GbSPA==,type:str]
    STORAGEBOX_HOST: ENC[AES256_GCM,data:R92iVj5GeoPbtqbeetAWW6dWD70XMK+cNZQ=,iv:CWJzop8s3eGLXlaI9WbOfwHNLeuoAjcZzQS1tgJLThA=,tag:IBnsjIwnC7CTFFV9dgqOKA==,type:str]
    STORAGEBOX_USER: ENC[AES256_GCM,data:eajqST7Ptw==,iv:+5YJsZ+hIYlW0W378YboPMoDESfNiNABbTH/6mtJFBI=,tag:S7os9UsK/VQxst53fs1Ckw==,type:str]
    STORAGEBOX_PASSWORD: ENC[AES256_GCM,data:71jlN91yjyUZSX8NedUAJNyBjIjk2iCDQb75jJCdQBM=,iv:tv5lgJd2EY3Zvq9g4EE738JtjqBkRc6Ynp58XPtJTMs=,tag:cOFzd0J9KnyCPXOSOYMJww==,type:str]
    FLY_READ_TOKEN: ENC[AES256_GCM,data:uiW+VvMnKDkVsLWsR3ZHBS0TPhOTuMG7YvYUBlUUouU0H6ZhyBrQlvsYYvDRy7568y43KXfP6Xpj3hdsfF5ULeT73Rl0XtmRGnj31dhBIrLHobeLoqHcOb5jyvbh1D646NEUAaW4j6RHJIr4QpcHmg8niHamnoQ3ZrekNl1djRNzXmDpqqQIuJUijuZ+/qvLsBIqys6Hk0pk581e5qTfyZ5p5OogZ3mYNLFai1TsS4LeU/LNH0aGgCik9O5DL4DLsDzI2paF42P4phIsyojkk+BBZGArJWRfXCnjXj056lK2+chqkGqVnqTca4V5JKyR3I4gF0gVnv3x9ILlfzD+LU4Lv1hiafSAlzcL3gm5gvKXoPXPUDecNoz93kocpt5XtL5N7Lq75dyFnPfINDOnaoQc/jafVa7elyOuykkjOPNtAruAY6AToAprVpfU0VnOPEevfQADIUXIir77KRZYSxmWHtbeQpuY5hSFBJPGCtvJREuynx1Bnx2FlK8XjtCPw72mBkspbZP4HFQytkQS+bvs+GN4aDrmZrsBF1sEBSGzavbrfLF7fr7F6F8QPj9Qy5U7NSqsz7RLxEXjh0r7pvSizFwpVqfsx7cO1yRKXj+0xq7m7z9lKnMF7/G0BxZP5P5bkBTNu903vcRpOpkXxMWnlkXfrFHHLUCJk1Kw8m93PLMHSdFBtQyOnQ6ZHVkmTik6RqjyOMM6+6jmyLptRA/LFevDdG1gZIUnio4VXW9Bb/xuGvxlkBRWRsdHHWH/e1MeZ+oDIdzkgF1wAUGSAyznRTRprLQ5wIeqtfsagLTo0AqNsEZtJfq2wLxUEB8/dhtblCmV9Jc6WEXNdkodhPpOBGfm4Y6DbqKhWqoOnBVN/90=,iv:Y9hH8DSgk89yqSA6SEQHN27z4Pn46JDTlAkcl4lTVuc=,tag:XZZpHkkTyFnbyFgOQw2SEQ==,type:str]
    JARVIS1_CREDENTIALS_ID: ENC[AES256_GCM,data:DVBdkN0xQoKXf2Wn+ctMYYtg4twfaYoAThiJ9/jP0lLv9U8hTtiS,iv:dxNME/pjvD+9SqMwgXUmuOAjEnCimGJB6I3mDOnUTPI=,tag:mnzrS/n8+twSln6hZaC0AA==,type:str]
    JARVIS1_CREDENTIALS_SECRET: ENC[AES256_GCM,data:3dLTRf95kzNwDKAc84HFWtb/orRhXTxpdUiF0KnbHRw2Ct0FdD4s3iKo6hboyyp708G7cv2n,iv:axdR3MzFm5HH4pAFZag5xaKQokIB1Ok9jHvF5HBK0l0=,tag:YXtb359j+DGEcSjcV2aREQ==,type:str]
    JARVIS1_SERVICES_ID: ENC[AES256_GCM,data:O28AO6R3oAAKS3NLezJMMPfgR+pHQSknTaqdc3QrFVLlg4dGFbp6,iv:aEdNq8zs/dD7XJVy4PRz/2+36h/LJHY8DomqbRe+ik8=,tag:2154WByw+gmTY/nuWxHtDw==,type:str]
    JARVIS1_SERVICES_SECRET: ENC[AES256_GCM,data:N1Twk+EzrYLXSDwOUAhUbMQcKbt0FrzBnKuUnjMjsn8dA5yvAokkIdYBhDxq5h1I56nPsA2+,iv:DsEAzCpjkWUF/x3BCWuSgKaM8jR1f5y3tLsD+lpr/jg=,tag:tsK0S//EgiJHT6IGKJ/20w==,type:str]
    GITHUB_READ_TOKEN: ENC[AES256_GCM,data:2v73IqXuAGXBfezBdwH3SZYl2+QcUIcquPYKQ7XOz3FTT8vDPf8QG+sMb/1yBm7q7jb9g0YzQwgfgVw2TtaMjA0qwszvwHU9aBRVEXdQO1achnUfgMGmvaw0IXB0,iv:VsZtfps+2FQUNhpjsrGLURq8X9+0Dgq0rGgLzQ0dr3Q=,tag:dlLJi7LUWV+O9yZeygfa8Q==,type:str]
    JARVIS2_TUNNEL_KEY: ENC[AES256_GCM,data:bFx0m8Oj48WXXzr7gOO8ibNAkGRd2DBLlaEkoiWaUZMb7rnU/KDwnjbjgN8NaxNhaCDDRIVYm/F+1x/lXJtVew==,iv:U9Rmh/5SPzocNjZ3fRKr9/MwhaNcgUWcN2zK+TJBvxo=,tag:PlxXGEJ7gIn228Sy8gugKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb0M3UTBzcEh2YlIySFM2
            MENEK0kyUXhpdm9abDN4bTlPWGhJYVhNWmlRCng3YzJNcWZtNUpXeDhNVUdwdVhG
            QnZVRWRqL3VkMW9wSllyN2xTWlBDWG8KLS0tIDZhOXVXNEdxYTRkazdhY3pmYVBD
            YkZRVjlUWkV3bXlIc05pOUp5TUFuZGsK0YvhzswwXAIj4rfXxKaC31dNMKBxmYRS
            bOGtcV9X09WLtbfrElJ9uq754bh9NyTtFiB3KAN1aojGLCstIPI0fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aft9s8atepzmgx8qfjpjndanxaj739k3y9vctycdtgxdhlg3uc8q4vy7pa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T08:51:47Z"
    mac: ENC[AES256_GCM,data:bsSc98I9E6WH529i5oJtTOdLLS8f0ZbwI8pzfek17hUo9Q6Ocn36PW+8b3yyKZ/Uy36x62Nu6hh7v9OYPtqltE02s607lSg67Dxo26cbb1XmoyfUsBcdEwy6z/l5PEsdqzBN6DFufQwUPMcc/Ee9EN4+f+rUTzEBqxbMevLzJh4=,iv:WeBRDjruY3oLtZrBrQbDcHB6Jz55LzYg8eJludD/IdE=,tag:mmJWl5GWd62Z0WoVWE6hpQ==,type:str]
    version: 3.13.3
