apiVersion: v1
kind: Secret
metadata:
    name: router-secrets-backup
    namespace: jarvis2-router
type: Opaque
stringData:
    BACKUP_READ_ACCESS_KEY: ENC[AES256_GCM,data:2S6Ui5VHXOIybeN9QGAdUYSxhWY=,iv:wsw5sz2UmSd9l6EhOotniHDwo+NZx2J5dptUvx7+UxY=,tag:C7/NqubRpMoIqtE8C8MjiA==,type:str]
    BACKUP_READ_SECRET_KEY: ENC[AES256_GCM,data:VRcO9VaPKuxHXct5uA4ZBlx8cl7GBWn7KMOtLyPjX79hxeDgDNsbyA==,iv:g/RrjU6isbRjUhzSPsrWPs0epHc/lOsBY/87TxR4VS4=,tag:ceIBOSFYzXOUKAZoUFSgGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUUNVU0c1YVBmYllOcndi
            K0ZTZTJqL09JOHhBY01BU0VNNTVpcEJzOWxnCit5QU5BbC9ObzRMQ0MrZFJIWi94
            RWJRdlFqSmJTSCtZZjE2YXZVUUxDRVkKLS0tIGloRnlnL1VhYmxnTHczdHFFcHpt
            UG1BbDZDajkrN1BvVEIvRnROWVVLS28KqzpoxOgImunuvySlTW3n7pzCctnVoJPK
            0a3bbg22EBo5GSzccnKWmp0yhCol5XpuxBcKD/eNcdmbP56IQR1c+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aft9s8atepzmgx8qfjpjndanxaj739k3y9vctycdtgxdhlg3uc8q4vy7pa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T15:11:20Z"
    mac: ENC[AES256_GCM,data:UBHkItZ1zHiY/cS1tmL8iunByNSohvXEROVbhRygG7gP8VjBp5CBj2EtrSLzv0sJ3URfiagj2K3tIg7VOtNdNVKn7liUyaGRADuv/scUWjji7ex09li1J1FX3Yqk+RByE3rhaDL7fIK5JxsEW5472Cyb4osO7SwIGqCbfOIgzoc=,iv:vEtFIAuQ5of1xPoG4gBU/HCcRC9mGE5Sri9a/Rax8cs=,tag:tfrx5/PQUlRFDuNotse+sQ==,type:str]
    version: 3.13.3
