apiVersion: v1
kind: Secret
metadata:
    name: router-secrets
    namespace: jarvis2-router
type: Opaque
stringData:
    LOBSTER_TOKEN: ENC[AES256_GCM,data:38UFLPegY92V5sIBbVuBKNq00zBADRv7nODFplXMDEY/jrQcF1r+lwt3R9shN+U7T0nhYa64iowCK750EHULmEd3BNkD72NL,iv:aDw4Eu9bVVtWyXsmnTdonlUw4MSelHggdiDDEHDgw6g=,tag:eFmS3Ijxgn3xEvM42EqyoQ==,type:str]
    STORAGEBOX_HOST: ENC[AES256_GCM,data:vs7sLbREZVIBi1SsGuRh+qgJ3Ew1A55QuyU=,iv:R3s6azJ/4DaWrPH8K6Yrq23iiy4KZBmGf+ovGP3yKDM=,tag:RNvoPOusuhYYGUXymB4VIQ==,type:str]
    STORAGEBOX_USER: ENC[AES256_GCM,data:bJKqkPt42g==,iv:apgjgXJReR4103t2wQ+2v2DuErcBYuhzWPhuLKZcUlc=,tag:icpvJPNpfQsGwbDhhrHQnA==,type:str]
    STORAGEBOX_PASSWORD: ENC[AES256_GCM,data:GwLiJnSHhwdtGmQb2M3F7MlTUtghJJimxmSTSdoCHW4=,iv:FWAfH8EwYuD4gbuLbQVNnnlUHSeiBy3Qtekx++g3QT8=,tag:WlcWvyag5BuWAR4wnknrFA==,type:str]
    FLY_READ_TOKEN: ENC[AES256_GCM,data:Nh9YL1gqXaQXm5klD5sHQ1ykBqY40hu5beT0RwWgT40C41ys9ztoriZtpECYqjdu4ZcrAA4g9frrStoVoZ3Etu8AAOtqu3wFjf+ZrJMOmDYw0WS5LXMTHpkCI9sOmfXXS/Cps79GgMDTckMiwRKuA/OKoE6uyUO5/o2XiU4JtB0/mTwWyzMQ6QxZryCOMnMeutoGtlph0nC4icgo3DjsLtKnTdS8hTekz3eUv3JcHFgImBnmBwMbkkVLkyTdM89NuowJirEVJ42EuIwGNFwpFY0IQjRhws4RwPUGUEiKp7SrSAXiDNCM7l26jlLhdrl/jAxSObL+JCvsZJTCtUzD6XMfJmXmc7KsnrZ8Gi8VUj/iyDKN+dc/B2wFVosPKeyG5pO+piYkEgS1YuMBgSOxplUFVTO4QpVUDyIGlnNv6BXrwscjvGNttBQ6CxLcvfSNZUAJsg1AQb+aXcv0yu8kezjO4hu+RbgDlOVq00BrTi+alYiYggvIsp2JLvdeD2N/noovqhyHpJE3uU8izV5z9LhcXbX4yXgOy4PAHoXQsXp/jCpGVG4tYoD8Ii+cqdtG/GKrz1oaynjGyFAABRYY/perSTKuSaADWcFvyc9hx/ka95/73ndlHDjAsTQVmPB4Z65asKc/HG8+0Ssiv1vfV2iq4Y34VJJWXrP+WCS/4T9a1SZd7BVJ0vjCveW1WcO7yw/csDQvJ4sc7z0TTLD7VUCw6CcfRYXrjWxlGhparSeWDCCwdLnB2J34HIKKNAphPs+v/kSaa1o2kZdzcshJeQLNnvq6FEO0i9r3jNiUFQMZHGBFjeVd4czAp6njTwzpArDqDEI5ZMVSIbXpoK5fcICzhh+mA10S05B4ScReFT2DP3o=,iv:zMEcpu4+6omJ4LaUx1cosq9zlVyOewuXa75FRUgG+SU=,tag:/8mb0j8o0AdunICd+E8Xdg==,type:str]
    JARVIS1_CREDENTIALS_ID: ENC[AES256_GCM,data:wb/1BDEi/CgH0ObSWZZdyP+Ktsx9gwNetoYz2+zkEt6bG1rLSzAj,iv:DqLTWvCu7VJt8+PuTtsurD0QyeF1QAQtiGM2M8w+RxI=,tag:MwIBfsmb4CHMYTvpvgtHnw==,type:str]
    JARVIS1_CREDENTIALS_SECRET: ENC[AES256_GCM,data:NN/FXwO+/czIBJDNhrfs9Io94SKokLjAr4xatRL32m1fkuxoXOxBPvesEYgxcq77oKBisbDm,iv:cmQ4qMBS22tfQH9bAOb/uyO4eWlEChP6sSCqT5dQDgg=,tag:veUXgqE9buBAbvbClFJpHQ==,type:str]
    JARVIS1_SERVICES_ID: ENC[AES256_GCM,data:11Pved+2g0ibBuB4kuQTwcYJPS95BDI0bwCVE5K1wcoxymakvjWD,iv:DQ+WX9Og7Lurfg2xJV+8IB+P3r6O3zwTRDOYc666z30=,tag:kZK/PRYyLKm7P3FHVDTQ1A==,type:str]
    JARVIS1_SERVICES_SECRET: ENC[AES256_GCM,data:nfKvmV4gDjDf7FDKIavjvEwVX/Tglxi+gqH1gm9y1+D0dN+jInaRjeBYU2pWwuDGUwsqj0hl,iv:EFm/ma2wXADpqx8M7bffGttzbYDAJC+83FDAV9KmEgY=,tag:PVcyJkZGk/s3SiI01VJlFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbXNjQVl1ZDdhbng0enc1
            U2d2c01sL3VicE1jYktNM2NuSXBLY3RKWUQ0CmgwOW5zSGQ3Mzd5bVREYmpCRk55
            T3paUXN2ZDNBU3EwS0hWZkIwWVFxVDgKLS0tIFY1aW5talNBaUNiZy9SWGJRb05z
            ZGFDc2wzT0dNZjNNUy9HMnlWazNibDAKdzqFp7KFPPVaWywEcl6x8wHkIauCRePq
            GJqPzAvOfpXqH7q9p4d8sUAaus5+6DV+N0oSJPTvNMq+lj1zGCZ0KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aft9s8atepzmgx8qfjpjndanxaj739k3y9vctycdtgxdhlg3uc8q4vy7pa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T08:38:08Z"
    mac: ENC[AES256_GCM,data:i9rtSuB1Pt0xmYQIpOGpTIlV0zVaMloRZgK8DK4AmXkIMSyc9lpuj8hX8znEshsGYwaz/o/y6cTiMOMu6TNnN5JhmbrykMrbzi+L84u1BVYupBEkjeZQUXTvZks5eaRN9PtX9XF7QiX1+1EadyHjR0yhSvkumOT3GmNqVO4dMtg=,iv:+uKcX8gpzS4AxP1+d9rX8a10gn40P60+5UH+vKBqnzI=,tag:LS1IeppRUPOJ8kUKcT+xjQ==,type:str]
    version: 3.13.3
