apiVersion: v1
kind: Secret
metadata:
    name: router-secrets-github
    namespace: jarvis2-router
type: Opaque
stringData:
    GITHUB_READ_TOKEN: ENC[AES256_GCM,data:GprYrsMs3QxhnWmSiShoD1Lv62Vak+uET86bNVKBZtNm7JUMbbj+vLlc5jKr7/wzVnvl+RLRufxPgm+GyXhUsS9NByRIR7kj6SDoGoBvd5pLlALvQYdsjiqlI40l,iv:TwIOlQkpzZKG/Nky9AjZ+jKgIb8X+Gv72yqOOXEGsz0=,tag:1VwRHA7ddw+ijJcCuCRfBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQREt2dDIvTlM1QVUxbnM2
            bDVVbE1nd2RTR1l1OFVtckVWK2sydk5QVG53CnVrbWdEZkUxcmhIK1dJbVVsQUVk
            RklYSVFOVmtPRDBPQ2REUE0yT0U4NlEKLS0tIGlQZzRUTFFPOHlyU3Y0cldPL21Z
            ZEdBYmhMZTJEYWl4bENlSHlGTVB0TGsK+32JI9bDKD08dTrmuP4euLjzyiCb/erN
            /PXj7X5WOjPjEX9SUZEiNbOeSKfvFsxr3W57e9OD0EvaZCtzYj+1vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aft9s8atepzmgx8qfjpjndanxaj739k3y9vctycdtgxdhlg3uc8q4vy7pa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-11T06:04:42Z"
    mac: ENC[AES256_GCM,data:xhMdHoIhKZJxjWl4gz/Y8/OltlEbvDPAvCa450XR1bPtOJHoPDovFKxIJ/OcEOWvjrfdwioT56MGeCq1h3xLQPb1fOPJsprdKwhD7PzZCH0xd7+D2HJqhFBHy/yc59CE+2fb4WyxYsQccrBsT4V2dcOsoS6rY10C13EWkwG5Zsc=,iv:kBrl8NisxJImzKi3vnsQSmTIWOsycRpgasR/x7zMGaw=,tag:nIT19t7X84ABcVndWvPeuw==,type:str]
    version: 3.13.3
